// web/src/app/layout/app-shell/app-shell.component.ts
import { Component, computed, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink, RouterOutlet } from '@angular/router';
import { MatToolbarModule } from '@angular/material/toolbar';
import { filter, map, startWith } from 'rxjs';

interface BreadcrumbItem {
  label: string;
  link: string[];
}

@Component({
  selector: 'app-app-shell',
  imports: [RouterOutlet, RouterLink, MatToolbarModule],
  templateUrl: './app-shell.component.html',
  styleUrl: './app-shell.component.scss',
})
export class AppShellComponent {
  private readonly router = inject(Router);

  private readonly url = toSignal(
    this.router.events.pipe(
      filter((event) => event instanceof NavigationEnd),
      map(() => this.router.url),
      startWith(this.router.url),
    ),
    { initialValue: this.router.url },
  );

  readonly breadcrumbs = computed(() => this.buildBreadcrumbs(this.url()));

  private buildBreadcrumbs(url: string): BreadcrumbItem[] {
    const items: BreadcrumbItem[] = [{ label: 'Campagnes', link: ['/campaigns'] }];
    const parts = url.split('?')[0].split('/').filter(Boolean);

    if (parts[0] === 'campaigns' && parts[1]) {
      items.push({ label: parts[1], link: ['/campaigns', parts[1]] });
    }
    if (parts[0] === 'documents' && parts[1]) {
      items.push({ label: parts[1], link: ['/documents', parts[1]] });
    }
    if (parts[2] === 'chunks' && parts[3]) {
      items.push({ label: `Chunk ${parts[3]}`, link: ['/documents', parts[1], 'chunks', parts[3]] });
    }
    if (parts[2] === 'stat-blocks' && parts[3]) {
      items.push({
        label: decodeURIComponent(parts[3]),
        link: ['/documents', parts[1], 'stat-blocks', parts[3]],
      });
    }

    return items;
  }
}

<div class="app-shell">
  <mat-toolbar color="primary" class="toolbar" data-testid="app-toolbar">
    <a routerLink="/campaigns" class="brand" data-testid="app-brand">RPG Assistant</a>
    <nav class="breadcrumbs" aria-label="Fil d'Ariane" data-testid="breadcrumbs">
      @for (item of breadcrumbs(); track item.link.join('/'); let last = $last) {
        @if (!last) {
          <a [routerLink]="item.link">{{ item.label }}</a>
          <span class="sep" aria-hidden="true">›</span>
        } @else {
          <span class="current">{{ item.label }}</span>
        }
      }
    </nav>
  </mat-toolbar>
  <main class="content">
    <router-outlet />
  </main>
</div>

// web/src/components/layout/AppShell.tsx
import { Link, Outlet, useLocation } from "react-router-dom";

function crumbsFromPath(pathname: string) {
  const parts = pathname.split("/").filter(Boolean);
  const items: { label: string; to?: string }[] = [{ label: "Campagnes", to: "/" }];
  if (parts[0] === "campaigns" && parts[1]) {
    items.push({ label: parts[1], to: `/campaigns/${parts[1]}` });
  }
  if (parts[0] === "documents" && parts[1]) {
    items.push({ label: parts[1], to: `/documents/${parts[1]}` });
    if (parts[2] === "stat-blocks") {
      items.push({
        label: "Fiches stats",
        to: `/documents/${parts[1]}/stat-blocks`,
      });
      if (parts[3]) {
        items.push({ label: decodeURIComponent(parts[3]) });
      }
    } else if (parts[2] === "chunks" && parts[3]) {
      items.push({ label: `Chunk ${parts[3]}` });
    }
  }
  return items;
}

export function AppShell() {
  const location = useLocation();
  const crumbs = crumbsFromPath(location.pathname);
  const documentMatch = location.pathname.match(/^\/documents\/([^/]+)/);
  const documentId = documentMatch?.[1];

  return (
    <div className="app-shell">
      <header className="app-header">
        <h1>RPG Assistant</h1>
        <nav className="breadcrumb" aria-label="Fil d'Ariane">
          {crumbs.map((item, index) => (
            <span key={`${item.label}-${index}`}>
              {index > 0 && <span aria-hidden> / </span>}
              {item.to ? <Link to={item.to}>{item.label}</Link> : <strong>{item.label}</strong>}
            </span>
          ))}
        </nav>
      </header>

      {documentId && !location.pathname.includes("/stat-blocks") && (
        <nav className="sub-nav">
          <Link
            to={`/documents/${documentId}`}
            className={location.pathname === `/documents/${documentId}` ? "active" : ""}
          >
            Exploration
          </Link>
          <Link
            to={`/documents/${documentId}/stat-blocks`}
            className={location.pathname.includes("/stat-blocks") ? "active" : ""}
          >
            Fiches stats
          </Link>
        </nav>
      )}

      {documentId && location.pathname.includes("/stat-blocks") && (
        <nav className="sub-nav">
          <Link to={`/documents/${documentId}`}>Exploration</Link>
          <Link
            to={`/documents/${documentId}/stat-blocks`}
            className="active"
          >
            Fiches stats
          </Link>
        </nav>
      )}

      <Outlet />
    </div>
  );
}
